version: '3.8'
services:
  sadtalker:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./results:/home/SadTalker/results
    ports:
      - 10364:10364
    environment:
      - TTS_SERVER=http://tts:5002/api/tts
    command: uvicorn main:app --port 10364 --host 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10364/docs || exit 1"]
      interval: 60s
      timeout: 20m
      retries: 20
  
  tts:
    image: ghcr.io/coqui-ai/tts:latest
    ports:
      - 5002:5002
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: python3
    command: 
      - TTS/server/server.py
      - --model_name
      - tts_models/en/vctk/vits
      - --use_cuda
      - "true"

  nginx:
    image: nginx:alpine
    ports:
      - 4500:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

